version: '3'

services:

  db:
    image: postgres
    restart: always
    networks:
      - confluent_network
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/mypc/dev/java/kafka/streams/streams.examples/docker/data/postgresql:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - confluent_network
    ports:
      - 8080:8080

networks:
  confluent_network:
    external: true

